Repository 2024-EveryCare/frontend, pull requests merged in 2024-08, with the labels that each got.

#105 OCR인식, OCR인식후 최종저장 API연동완료
  src/assets/dad.png
  src/assets/mom.png
  src/components/myPage/Profile.tsx
  src/components/register/DirectScan.tsx
  src/components/register/ScanConfirm.tsx
  src/main.tsx
  src/pages/mypage/Menu.tsx
  src/pages/mypage/MyPage.tsx
  src/service/submitOcrFile.ts
Labels: 🔧 Feature

#107 달력 페이지 API 연동
  src/assets/Calendar/Lunch.svg
  src/assets/Calendar/Morning.svg
  src/assets/Calendar/Night.svg
  src/components/Calendar/CalMockData.ts
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarInfo.tsx
  src/components/Calendar/CalendarTable.tsx
  src/components/register/DirectRegister.tsx
  src/utils/date.ts
Labels: 🔧 Feature

#149 메시지 내역 화면 길이 수정
  src/components/AiChemist/Chat.tsx
Labels: 🪄 Refactoring

#150 후속조치 사항 수정.
  src/assets/Chatbot.textClipping
  src/assets/chatBot/Bubble.png
  src/assets/chatBot/Chatbot.png
  src/assets/chatBot/Chatbot2.png
  src/assets/chatBot/bubble2.png
  src/assets/chatBot/bubble3.png
  src/components/AiChemist/Chat.tsx
  src/components/login/LoginForm.tsx
  src/components/register/DirectRegister.tsx
  src/components/register/ScanConfirm.tsx
  src/pages/AiChemist/AiChemistPage.tsx
  src/pages/calendar/CalendarPage.tsx
  src/pages/calendar/ScanOrDirectPage.tsx
  src/pages/mainPage/MainPg.tsx
  src/pages/mypage/Menu.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/pillinfosearch/PillDetailSearchPage.tsx
  src/pages/pillinfosearch/PillInfoSearchPage.tsx
  src/pages/register/DirectRegisterPage.tsx
  src/pages/register/DirectScanPage.tsx
  src/pages/register/PillRegisterPage.tsx
  src/pages/register/PillSearchPage.tsx
  src/pages/register/ScanConfirmPage.tsx
  src/pages/register/ScanOrDirectPage.tsx
  src/utils/cookie.ts
Labels: 🪄 Refactoring

#153 달력페이지 챗봇 위치 조정
  src/pages/calendar/CalendarPage.tsx
Labels: 🪄 Refactoring

#156 삭제 기능 오류 수정
  src/components/Calendar/CalendarInfo.tsx
  src/service/deleteDrug.ts
Labels: ⚒️Bugfix

#157 Refactoring/#155 챗봇 텍스트 수정
  src/assets/chatBot/bubble2.png
  src/assets/chatBot/bubble3.png
  src/pages/register/PillSearchPage.tsx
Labels: 🪄 Refactoring

#160 삭제 기능 불필요한 코드 삭제, 약봉투 등록 페이지 코드 오류
  src/components/Calendar/CalendarInfo.tsx
  src/components/register/ScanConfirm.tsx
Labels: 🔧 Feature

#165 배포 url 수정
  src/service/config.ts
  vite.config.ts
Labels: 🪄 Refactoring
