Repository 2024-EveryCare/frontend, pull requests merged in 2024-05, with the labels that each got.

#6 약 직접 입력 퍼블리싱
  src/assets/SearchIc.png
  src/components/button/Btn1.tsx
  src/components/button/Btn2.tsx
  src/components/register/PillNextText.tsx
  src/components/register/PillSearch.tsx
  src/components/register/button/BackBtn.tsx
  src/main.tsx
  src/pages/register/DirectRegisterPage.tsx
  src/pages/register/PillRegister.tsx
  src/pages/register/PillSearchPage.tsx
Labels: 🖼️ Publishing

#9 Style/#2 복용내역 퍼블리싱
  package-lock.json
  package.json
  src/assets/Calendar/Calendar.svg
  src/assets/Calendar/Pill.svg
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarInfo.tsx
  src/components/Calendar/CalendarTable.tsx
  src/components/Calendar/Modal.tsx
  src/components/CenterLayout.tsx
  src/components/NavBar.tsx
  src/hooks/useCalendar.tsx
  src/pages/scan/CalendarPage.tsx
  src/styles/reset.css
  src/utils/helpers.ts
Labels: 💖 Style

#10 Style/#3 NavBar 오류 해결
  index.html
  package-lock.json
  package.json
  src/components/CenterLayout.tsx
  src/components/NavBar.tsx
  src/main.tsx
  src/pages/calendar/CalendarPage.tsx
Labels: ⚒️Bugfix
