Repository 2024-EveryCare/frontend, pull requests merged in 2024-06, with the labels that each got.

#12 메인화면 퍼블리싱, 라우터 설정
  package-lock.json
  package.json
  src/assets/mainPage/CalendarGroup.svg
  src/assets/mainPage/SearchBar.svg
  src/assets/mainPage/SmallPill.svg
  src/assets/mainPage/main1.svg
  src/assets/mainPage/main2.svg
  src/assets/mainPage/main3.svg
  src/assets/mainPage/main4.svg
  src/components/mainPage/MainPage.tsx
  src/main.tsx
  src/pages/mainPage/MainPg.tsx
Labels: 💖 Style

#15 로그인 퍼블리싱 수정
  package-lock.json
  package.json
  src/assets/login/Bg1.svg
  src/assets/login/Bg12.svg
  src/components/CenterLayout.tsx
  src/components/login/LoginForm.tsx
  src/pages/calendar/ScanOrDirectPage.tsx
  src/pages/login/LoginPage.tsx
Labels: 🖼️ Publishing

#26 약봉투 큐알스캔, 직접파일 업로드 페이지 퍼블리싱
  src/components/register/DirectScan.tsx
  src/components/register/ScanOrDirec.tsx
  src/pages/register/DirectScanPage.tsx
Labels: 🖼️ Publishing

#42 OCR확인 후 서버로 PUT요청 API구현
  src/components/register/DirectScan.tsx
  src/components/register/ScanConfirm.tsx
  src/components/register/button/SaveBtn.tsx
  src/pages/register/ScanConfirmPage.tsx
Labels: 🔧 Feature
